service: trade-results

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-1
  logRetentionInDays: 30
  memorySize: 128
  timeout: 10
  # apiGateway:
  #   usagePlan:
  #     quota:
  #       limit: 5000
  #       offset: 2
  #       period: MONTH
  #     throttle:
  #       burstLimit: 200
  #       rateLimit: 100

plugins:
  - serverless-domain-manager
  - serverless-resource-policy

custom:
  customDomain:
    domainName: results.billmcmath.co.uk
    basePath: ''
    certificateName: '*.billmcmath.co.uk'
    stage: ${self:provider.stage}	
    endpointType: 'regional'
    createRoute53Record: true
  serverless-resource-policy:
    stage: ${self:provider.stage}
    privateStages:
      - dev
    netblocks:
      - 82.42.77.15/32

functions:
  exampleFunction:
    handler: handler.handleRequest
    events:
      - http:
          path: '/'
          method: post
          private: false
